* Python Library for working with arrays
* Applications: Linear algebra, fourier transform, matrices
* NumericalPython
* The array object is called ndarray.


### Benefits

* 50x faster than traditional python lists.

* NumPy arrays are stored at one continuous place in memory unlike lists. Easy access>> Faster Processing
* Written partly in python , mainly in c/c++

In [3]:
import numpy as np

###### 1D Arrays 

In [4]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


###### 2D Arrays

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


###### 3D Arrays 

In [6]:
c = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [7]:
print(c.ndim)

3


###### NumPy Array Indexing

In [8]:
d = np.array([1, 2,3,4])
print(d[3])

4


In [9]:
print(b[1,0])

4


In [10]:
print(c[0,1,1])

5


###### Array slicing 

* In Python, Slicing means taking elements from one given index to another given index.
* [start:end]
* [start:end:step]
* default start index = 0
* default end index = Length of array in that dimention
* default step = 1

In [12]:
print(a[:2]) # Slice index from the start of the array

[1 2]


In [11]:
print(a[2:]) #Slice index from the end of the array

[3 4]


###### Negative slicing

In [13]:
print(a[-2:-1])

[3]


###### Step Value in slicing

In [14]:
print(a[0:4:2])

[1 3]


In [16]:
print(a[::2]) #return every other element from the entire array

[1 3]


######  Slicing 2D Arrays

In [18]:
print(b[1, :2]) # from the second element, slice from the beginning index 0, 1 (Excluding index2)

[4 5]


In [22]:
print(c[0:2, 1]) #from  elements 0, 1,2 return index 1

[[4 5 6]
 [4 5 6]]


### Data Types In Numpy 

* i = integer
* b = boolean
* u = unsigned integer
* f = float
* c = complex float
* m = timedelta
* M = datatime
* O = object
* S = sting
* U = unicode string
* V = fixed chunk of memory for other type(void)

In [24]:
print(c.dtype)

int64


###### Defining Data type of array 

ValueError is raise when the type of passed argument to a function is unexpected/incorrect

In [25]:
e = np.array([1, 2, 3, 4], dtype = 'S')

In [28]:
print(e)
print(e.dtype)

[b'1' b'2' b'3' b'4']
|S1


##### Converting Data type on Existing Arrays 

* Make a copy of the subject array with astype() method.
* astype() creats copy of the array and allows to specify the data type as a parameter.


In [35]:
f = np.array([1.1, 2.1, 3.1, 4.1, 5.1])
fc = f.astype('i') #int will also work
print(fc)
print(fc.dtype)

[1 2 3 4 5]
int32


#### Difference between Copy and view 

* copy is a new array | view is view of original array
* Copy owns the data and any changes mad to the copy will not affect original array and vice versa.
* View doesn't own the data and any changes made to the view will affect the original array and vice versa.


In [34]:
g = f.copy() #Saving the original array
f[0] = 42 #making changes in original array

print(g) # the original array is showed without change
print(f) # The original array is changed and saved in its original place

[1.1 2.1 3.1 4.1 5.1]
[42.   2.1  3.1  4.1  5.1]


In [37]:
h = f.view() # peeped whats in original array
f[0] = 12 # made change in original array

print(f) # The original array with changes
print(h) # the method view is still peeping and telling whats in original array now

[12.   2.1  3.1  4.1  5.1]
[12.   2.1  3.1  4.1  5.1]


###### Check if array owns its data 

In [38]:
print(f.base)
print(h.base)
print(g.base)

None
[12.   2.1  3.1  4.1  5.1]
None


#### Array Shape

Shape of array is number of elements in each dimention

In [39]:
print(f.shape)

(5,)


In [41]:
print(c.shape) #this array is 2X2 with 3 elements in each

(2, 2, 3)


###### Array Reshaping


* Reshaping the shape of an array.
* The shape of an array is the number of elements in each dimention.
* By reshaping , we can remove dimentions or change number of elements in each dimention.

###### 1D TO 2D

In [43]:
i = np.array([1,2,3,4,5,6,7,8,9,10,12,13])
iresh= i.reshape(4, 3) # 4 arrays with 3 elements each
print(iresh)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 12 13]]


###### 1D TO 3D

In [44]:
iresh3d = i.reshape(2,3,2) #12= (2x2)x : 2 rows, 2 columns and 3 channels
print(iresh3d) #contains 2 arraysm 3 arrays each with 2 elements

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [12 13]]]


* An array can be reshaped in any shape, provided the elements required for reshaping are equal in both shapes.
* EXAMPLE: 1D array of 8 elememts can be reshaped in 2 row- 2D array.
__=>__ but not with 3 elements 3 rows 2D array as it require 3x3=9 elements

In [45]:
print(iresh3d.base)

[ 1  2  3  4  5  6  7  8  9 10 12 13]


The reshape array is a view array

### Unknown Dimention 

* Numpy can calculate the dimention for exact number for one of the dimentions in the reshape method.
* Pass -1 as argument

In [49]:
j = i.reshape(2,3,-1) #gives 2 arrays with 3 rows each
print(j)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [12 13]]]


###### Flattening the arrays 

* Flattening array corresponds to coverting N-dimentional array into 1D.
* used reshape(-1)

In [51]:
l= j.reshape(-1)
print(l)

[ 1  2  3  4  5  6  7  8  9 10 12 13]


Iterating Arrays

* Going through elements one by one.
* use for loop
* if we iterate o a N-D array , it will go through N-1th dimention one by one.

In [53]:
for x in j:
    print(x) #in 2D array, it goes through the rows

[[1 2]
 [3 4]
 [5 6]]
[[ 7  8]
 [ 9 10]
 [12 13]]


In [54]:
for x in l:
    print(x) 

1
2
3
4
5
6
7
8
9
10
12
13


#### Iterating 3D Arrays 

* In a 3D array it will go through all the 2D arrays.

In [55]:
k = np.array([[[1,2,3],[4,5,6]], [[7,8,9], [10,11,12]]])
for x in k:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


### nditer() : advanced iteration method 

* nditer() is helping function that can be used for basic -> advanced iterations.
* Solves some basic issues which we face in iterations.

* in basic for loops, iterating through each scalar of an array, we need to use n for loops which can be difficult to write for arrays with very high dimentionality.

In [57]:
for x in np.nditer(k):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


### Iterating array with different data types 

In [62]:
for x in np.nditer(k, flags = ['buffered'], op_dtypes = ['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'8'
b'9'
b'10'
b'11'
b'12'


#### Iterating with different step Size

In [64]:
for x in np.nditer(k[:, ::2]): #iterate through every scalar element of the 2D array skipping 1 element
    print(x)

1
2
3
7
8
9


### Enumerated Iteration using ndenumerate() 

* Enumeration means mentioning sequence number of somethings one by one.
* ndenumerate() is used for listing corresponding index of the element while iterating.


In [65]:
for idx, x in np.ndenumerate(k):
    print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(1, 0, 0) 7
(1, 0, 1) 8
(1, 0, 2) 9
(1, 1, 0) 10
(1, 1, 1) 11
(1, 1, 2) 12


### Joining Array 

* Joining means putting contents of two or more arrays in a single array.
* In SQL, we join tables based on a key, whereas in numpy, we Join arrays by axes.
* we pass a sequence of arrays that we want to join to the __concatenate()__ function, along with the axis.
* If axis is not explicitly passed, it is taken as 0.

In [66]:
m = np.array([1,2,3])
n = np.array([4,5,6])
o = np.array(['apple', 'banana', 'strychnine'])


In [69]:
mn = np.concatenate((m,n))
print(mn)

[1 2 3 4 5 6]


In [70]:
mo = np.concatenate((m,o))
print(mo)

['1' '2' '3' 'apple' 'banana' 'strychnine']


###### Lesson Learned:

any kind of array can be concatenated

### Joining Arrays using Stack Functions 

* Stacking is same as concatenation , the only difference is that stacking is done along a New Axis.
* Concatenate 2 1-D arrays along the second axis which would result in putting them one over the other , i.e., stacking.

In [72]:
p = np.stack((m,n)) n
print(p)

[[1 2 3]
 [4 5 6]]


In [74]:
p = np.stack((m,n), axis =1)
print(p)

[[1 4]
 [2 5]
 [3 6]]


###### Observation:


* default axis = 0: x-axis
* axis =1: y-axis

##### Numpy provides a helper function: hstack() to stack along rows. 

In [76]:
q = np.hstack((m,n))
print(q)

[1 2 3 4 5 6]


###### Numpy provides a helper function: vstack() to stack along columns.

In [78]:
r = np.vstack((m,n))
print(r)

[[1 2 3]
 [4 5 6]]


In [79]:
q = np.dstack((m,n))
print(q)

[[[1 4]
  [2 5]
  [3 6]]]


### Splitting array 

* Reverse to Joining/Concatenation
* Merges multiple arrays into one and splitting breaks one array into multiple.
* We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.


In [82]:
s= np.array_split(q, 4)
print(s)

[array([[[1, 4],
        [2, 5],
        [3, 6]]]), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64)]


In [83]:
print(s[0])

[[[1 4]
  [2 5]
  [3 6]]]


In [84]:
print(s[1])

[]
