* Python Library for working with arrays
* Applications: Linear algebra, fourier transform, matrices
* NumericalPython
* The array object is called ndarray.


### Benefits

* 50x faster than traditional python lists.

* NumPy arrays are stored at one continuous place in memory unlike lists. Easy access>> Faster Processing
* Written partly in python , mainly in c/c++

In [1]:
import numpy as np

###### 1D Arrays 

In [2]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


###### 2D Arrays

In [5]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


###### 3D Arrays 

In [7]:
c = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
print(c)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
print(c.ndim)

3
